### ISSUE TITLE
iOS 11 issue - Crop frame is set wrongly

### ISSUE THREAD

**Issue by mugunth87** [TimOliver/TOCropViewController#190]
On iOS 11 beta 9 the crop frame is brought up around 20 pixels. Please find the attached image with the issue.
<img width="294" alt="screen shot 2017-09-06 at 9 33 05 pm" src="https://user-images.githubusercontent.com/16566598/30144903-5340ea96-934b-11e7-91df-b6466fadef94.png">

**Comment by TimOliver** [comment]
Hey @mugunth87! That issue was already reported in issue #184. I pushed a fix to `master` but haven't done a new CocoaPods build yet. Can you try pulling `master` and see if it's fixed on your end?

Thanks!

**Comment by ghazi256** [comment]
Thanks @TimOliver

**Comment by mugunth87** [comment]
Thanks @TimOliver It's fixed when i use the library from the master.

**Comment by TimOliver** [comment]
Cool! Thanks @mugunth87! I've pushed that build to CocoaPods now, so that should all be taken care of. :)

**Comment by JarvisTheAvenger** [comment]
@TimOliver  This issue still exists, I have updated library code.
![simulator screen shot - iphone x - 2018-02-19 at 12 59 02](https://user-images.githubusercontent.com/25341882/36366610-e354a31a-1574-11e8-86c8-7ca4fe8d715f.png)
