### ISSUE TITLE
Incorrect zoom scale and offset when cropping with a circular region

### ISSUE THREAD

**Issue by colinhumber** [TimOliver/TOCropViewController#198]
- [X] I have read this issue template and provided all possible information. 
- [X] I'm using CocoaPods and have run `pod update` before filing this issue.

---

## Hardware / Software

Which version of the library were you using? 2.1.0
Which version of iOS are you running? iOS 11
What model of iOS device were you testing on? iPad Air 2
If using CocoaPods, which version of CocoaPods are you on? 1.3.1

## Goals

To fetch a circular image useful for a profile pic.

## Expected Results

The image is initially displayed zoomed out, centered on the image.

Expected Image
![img_0125](https://user-images.githubusercontent.com/104855/30495963-41e36af0-9a0b-11e7-893c-64354ce50eb4.PNG)

## Actual Results

The image is displayed zoomed in on the top-left corner.

Incorrect Image
![img_0126](https://user-images.githubusercontent.com/104855/30495943-3342dd28-9a0b-11e7-9cf4-4fcf2c5d8b1e.PNG)

## Steps to Reproduce

This looks like a regression caused by commit `e0e33d119661f24a26778d92905001d53861baeb`. The previous commit, `705bfcd9cdff9822f486fc536a37825825131cfe` works fine. The current HEAD, `7ed0feb10552c1d8c60a18cc3a34c59b3607e1cd`, is having the issue as well.

Not sure what kind of image specifically causes this, but the image I'm having troubles with is attached below. Seems like other images with different aspect ratios don't show the exact same behaviour, but aren't initially displayed as expected. Once the Reset button is tapped, however, all images revert to the expected behaviour.
![img_0111](https://user-images.githubusercontent.com/104855/30496497-c96e33a0-9a0c-11e7-8af1-0ebee1cabd45.JPG)

**Comment by TimOliver** [comment]
Oh dear. Thanks so much for reporting that and for providing a test image Colin! I'm sorry you ran into that issue.

I'll have a play with it tomorrow and see if I can work out what is causing it. I was playing with the content inset code in order to support the title label in that commit (Which came in handy when adding iPhone X support), which might explain it.

Thanks again for the heads-up!

**Comment by colinhumber** [comment]
No probs! Thanks for digging into this so quickly!

**Comment by TimOliver** [comment]
Hey Colin! Sorry about the delay. I only had a chance to check it now.

It looks like it's a bit of unexpected behavior in iOS 11 and how the controller is being presented in that popover. When it's initially presented, it's presented at full screen first (1024x768) and then quickly downscaled to the popover size.

The problem is that the code to calculate the center of the photo happens while the view controller is still at 1024x768, which is why it's initially misaligned.

It's probably a relatively easy fix to delay the calculation until the resize has completed, but I'll need to be thorough to make sure that doesn't end up breaking other stuff in the process.

Thanks again for the heads-up!

**Comment by TimOliver** [comment]
Alright. I THINK it's fixed now. There was extra strangeness in there where the safe area insets weren't being factored in properly too, so I had to move a few things around.

It's all checked into `master`. Please pull the latest and see if that's working for you now. :)

**Comment by inPhilly** [comment]
This is still happening in the 2.1.0 version, on an iOS simulator for iPad Pro 10.5 inch, iOS 10.3, using the images in the simulator.
