### ISSUE TITLE
'CALayer position contains NaN: [nan nan]'

### ISSUE THREAD

**Issue by Md-Sadham** [TimOliver/TOCropViewController#254]
When am trying to init the Crop view controller through popoverPresentationController in iPad device, Am facing below two issues. Actually I need to show initial image in crop view controller before the image picker.

Code:
```
self.croppingStyle = .circular
                let cropController = CropViewController(croppingStyle: self.croppingStyle, image: self.profliePicImageView.image!)
                cropController.delegate = self
                
                cropController.modalPresentationStyle = .popover
                cropController.preferredContentSize = CGSize(width: 320, height: 568)
                let imagePickerPopOverPresentationController = cropController.popoverPresentationController
                imagePickerPopOverPresentationController?.delegate = self as? UIPopoverPresentationControllerDelegate
                imagePickerPopOverPresentationController?.permittedArrowDirections = .up
                imagePickerPopOverPresentationController?.sourceView = self.profliePicImageView
                imagePickerPopOverPresentationController?.sourceRect = self.profliePicImageView.frame
                
                //If profile picture, push onto the same navigation stack
                if self.croppingStyle == .circular {
                    self.present(cropController, animated: true, completion:nil)
                }
```

Issues:

> [Snapshotting] Snapshotting a view (0x7fe48be321b0, TOCropToolbar) that has not been rendered at least once requires afterScreenUpdates:YES.
> *** Terminating app due to uncaught exception 'CALayerInvalidGeometry', reason: 'CALayer position contains NaN: [nan nan]'

Any idea what is the problem and how can I fix it?

**Comment by TimOliver** [comment]
Hi @Md-Sadham! That usually implies that the image that was supplied was empty (ie it's size was 0x0). I've tried to add checks to avoid this, but somehow it keeps slipping through the cracks.

Please ensure that you supply a valid image to the crop view controller before you try to present it. If you are, please attach the image here so I can test it myself. :)

**Comment by TimOliver** [comment]
Hopefully this was resolved in the end. :)

**Comment by matt-curtis** [comment]
Tested this today myself. The same issue is still present, even when using an image whose size is greater than zero. Only happens with popovers. The issue appears to be that somehow `cropBoxFrame` enters an invalid state during presentation.

**Comment by matt-curtis** [comment]
You're not able to reproduce this using `cropController.modalPresentationStyle = .popover`?

**Comment by matt-curtis** [comment]
Wow, that's surprising... I'll test the one from master. Thanks for looking into it.
