### ISSUE TITLE
Crop image and cancel In iPad throws exception

### ISSUE THREAD

**Issue by sridharmari** [TimOliver/TOCropViewController#361]
I pick an image and crop it, when cancel button  is pressed the app is crashing.
It is working fine in iPhone but exception throws in iPad.
Terminating app due to uncaught exception 'NSGenericException', reason: 'Your application has presented a UIAlertController (<UIAlertController: 0x7f8cfc0d6800>) of style UIAlertControllerStyleActionSheet from TOCropViewController (<TOCropViewController: 0x7f8cfb8f8c00>). The modalPresentationStyle of a UIAlertController with this style is UIModalPresentationPopover. You must provide location information for this popover through the alert controller's popoverPresentationController. You must provide either a sourceView and sourceRect or a barButtonItem.  If this information is not known when you present the alert controller, you may provide it in the UIPopoverPresentationControllerDelegate method -prepareForPopoverPresentation.'

**Comment by TimOliver** [comment]
Oh dear! You're right @sridharmari! Thanks for reporting that!

I've just pushed a new version that should hopefully resolve that. Can you please grab the latest copy and try it for me?

Thanks a lot!

**Comment by sridharmari** [comment]
Hey Tim, Thanks for looking in to the issue. It has not resolved yet.

Change this line for iPad and the crash is not happening now.

if ( UI_USER_INTERFACE_IDIOM() == UIUserInterfaceIdiomPad )
    {
        cropController.showCancelConfirmationDialog = NO;

    }
    else{
        cropController.showCancelConfirmationDialog = YES;

    }
