### ISSUE TITLE
Screen is going all blue after clicking on done button in iOS 13

### ISSUE THREAD

**Issue by pawargb** [TimOliver/TOCropViewController#393]
After crop when I click on Done button then all screen is going blue

**Comment by ghb101** [comment]
I am experiencing the same issue with iOS 13.  After tapping the Done button the screen just showings all black and doesn't return to the app. I have updated to the latest 2.5.2 version and this issue still persists.  The app does not crash, just stuck on the black screen so I need to close the app.  When I restart the app it shows the image correctly cropped, so it seems there is some issue returning to the calling app from the CropViewController after tapping Done.

**Comment by pawargb** [comment]
This is because card view presentation in iOS 13. Fixed using below:

https://stackoverflow.com/a/58255416

**Comment by ghb101** [comment]
Thanks.  I was using
   cropViewController.modalPresentationStyle = .popOver

This works fine for iPad devices.  But not for iPhone devices in iOS 13.
So I need to force modalPresentationStyle to fullScreen for phone device now.

**Comment by ghb101** [comment]
I've found that if I change  self.dismiss(animated: true, completion: nil) to   self.dismiss(animated: false, completion: nil) (set animated to false) in the didCropToImage function in my app, then all works well, even with the popOver presentation style, so I'll go with that for now.

**Comment by shamikagasc** [comment]
I have also experienced this issue,  thanks for the workaround. Wondering when this is going to be fixed for iOS 13

**Comment by hellojeffy** [comment]
+1 animating dismiss definitely looks much better! Would love to see this fixed for iOS 13

**Comment by TimOliver** [comment]
Hey folks! I’ve double-checked and the modal presentation style is explicitly set to full-screen in the library now.

Please try pulling from master and let me know if it’s actually fixed for you or not.

**Comment by shamikagasc** [comment]
@TimOliver this is now fixed. thanks so much

**Comment by TimOliver** [comment]
Cool! Thanks for confirming that for me @shamikagasc! I'll close this issue off now.

One final thing. If you're enjoying this library and are using it in a shipping app, and need extra support for it, please consider [sponsoring me on GitHub Sponsors](https://github.com/sponsors/TimOliver). Thanks! :D

**Comment by Skoua** [comment]
This is not fixed if you're presenting the crop controller from a modal controller.
Dismissing without animation still works though.

**Comment by Hamna21** [comment]
@TimOliver The issue is still not fixed, even with the latest pod.

**Comment by TimOliver** [comment]
Sorry folks. Please don't comment on a closed issue.

If the issue is still persisting on the latest release, please open a new issue, and please fill it with as much sample code/screenshots/information that I can use to reproduce it.

Thanks!
