### ISSUE TITLE
Duplicate UUIDs when installing via CocoaPods

### ISSUE THREAD

**Issue by TimOliver** [TimOliver/TOCropViewController#437]
This issue is a fresh start from issue #424.

It seems that our efforts to support SPM (Which involved setting up a series of symlinks to the Objective-C headers) ended up causing an issue in CocoaPods where pod installations will mention duplicate UUIDs.

I *think* this should be as easy to fix as ensuring that CocoaPods avoids the `include` folder with the header symlinks in it.

I sadly don't have the time to play with trying to find the right solution to this (Between work and preparing to travel back home), so if you're experiencing this problem and are in a position to test it yourself, any help would be appreciated. :)

Thanks!

**Comment by TimOliver** [comment]
This should be fixed now. Thanks so much to @regularberry for the PR!

**Comment by dvdblk** [comment]
I have just installed TOCropViewController with cocoapods and got this warning. Don't think it's fixed :(

**Comment by regularberry** [comment]
@dvdblk Tim will have to push out another release before you’d see a change. Unless you installed from master?

**Comment by dvdblk** [comment]
@regularberry No, I haven't installed from master so yes, you're right. Thought master was up-to-date with the latest release. My bad :)
