### ISSUE TITLE
Wrong button alignment in iOS 26

### ISSUE THREAD

**Issue by goodman-capu** [TimOliver/TOCropViewController#611]
**Describe the bug**
The action buttons are not aligned with Cancel & Done button in iOS 26.
If the view is resized (e.g. rotated), the buttons are aligned again. 

**To Reproduce**
Launch the crop view controller in iOS 26

**Expected behavior**
Buttons are aligned like iOS 18 & lower

**Screenshots**

<img width="400" alt="Image" src="https://github.com/user-attachments/assets/d6ed4a57-2e84-42e1-af66-b0956c6117c1" />

**iOS Device:**
 - Device: iPhone 16 Pro Max
 - OS: iOS 26 Beta
 - Library Version 2.7.4

**Additional context**
The same issue persists in iOS 26 Beta 2, 3 & 4

**Comment by TimOliver** [comment]
I'm still around. :) I'll do an iOS 26 pass when I can!

**Comment by TimOliver** [comment]
I just merged a new PR to main that should fix this. Please give it a try and let me know if that's working properly in your app now!

**Comment by goodman-capu** [comment]
Thank! I can confirm it's now working properly.

Do you want to wait until the official release of iOS 26 to see if the "fix" is still needed? From the PR it seem more like a iOS beta bug :)

**Comment by gregggreg** [comment]
> Thank! I can confirm it's now working properly.
> 
> Do you want to wait until the official release of iOS 26 to see if the "fix" is still needed? From the PR it seem more like a iOS beta bug :)

beta 8 is likely what will be released for iOS 26.0 and this is still happening, so it would be great to see this fix released when you can get a chance. Thanks so much.

**Comment by john-work-ios** [comment]
This bug is still there with the official release of iOS 26. The fix in the main branch works though! Thanks for that.
Any plan for Liquid Glass?

**Comment by john-work-ios** [comment]
@TillMoss what's the difference with the fix that's already in the main branch? Thanks!
